name: rescue
version: '0.2.0'
category: Error Handling
author: Brooklyn Zelenka
maintainer: hello@brooklynzelenka.com
copyright: © 2020 Brooklyn Zelenka
license: Apache-2.0
license-file: LICENSE
github: expede/rescue
tested-with: GHC==8.6.5
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  # Warn about too little
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  # Warn about too much
  - -Wredundant-constraints
  # Prettier Development
  - -fhide-source-paths

dependencies:
  - base
  - exceptions
  - ghc # for STM
  - mtl
  - transformers
  - unliftio # needed?
  - unliftio-core
  - world-peace

library:
  source-dirs: library

tests:
  rescue-doctest:
    main: Main.hs
    source-dirs: doctest
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - directory
      - directory-tree
      - doctest
      - Glob
      - lens-aeson
      - yaml

  rescue-test:
    main: Main.hs
    source-dirs:
      - library
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - hspec-core
      - hspec-expectations
      - rescue
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-hunit
      - tasty-hspec
      - tasty-smallcheck
      - tasty-rerun
      - transformers

  rescue-lint:
    main: Main.hs
    source-dirs: lint
    dependencies:
      - base
      - hlint
      - rio

benchmarks:
  rescue-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - criterion
      - rescue
